# Generated by Django 6.0.3 on 2026-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Shoe Name')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(verbose_name='Product Details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='shoes/', verbose_name='Shoe Photo')),
                ('is_available', models.BooleanField(default=True, verbose_name='In Stock?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
