# Generated by Django 6.0.3 on 2026-03-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='banner_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(upload_to='shoes/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
